apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tms0ksgpm-python
  janus-idp.io/tekton: tms0ksgpm-python
  backstage.io/kubernetes-id: tms0ksgpm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tms0ksgpm-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
