apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tms0ksgpm-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7c1085c6ea.n2dw.p3.openshiftapps.com/rhtap/rhtap-qe:314dff899be43ca9412c3e7d148ab972d15a8530@sha256:fcaefbbd46db072f5f43389c21a77d78c3f4fd2b284b42c90061c997cd17b5ef
          name: container-image
